ROKT/rokt-sdk-flutter

README.md

update readme to the current version

update readme to the current version

---

CHANGELOG.md
README.md
android/build.gradle
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
ios/rokt_sdk.podspec
lib/rokt_sdk.dart
lib/src/rokt_sdk_controller.dart
lib/src/rokt_widget.dart
pubspec.yaml

SDKs and interfaces updated
Version updated to 3.6.1

update SDKs and interfaces

---

.github/CODEOWNERS
.github/pull_request_template.md

add GitHub configs to this repository

add GitHub configs

---

android/src/main/kotlin/com/rokt/rokt_sdk/RoktWidget.kt
android/src/main/kotlin/com/rokt/rokt_sdk/RoktWidgetFactory.kt
lib/src/rokt_widget.dart

Added a nullable context in overridden function of RoktWidget
(https://rokt.atlassian.net/browse/MP-1582)

Added a nullable context

---

.circleci/config.yml
.gitignore
android/gradlew
example/android/.gitignore
example/android/gradlew
example/integration_test/app_test.dart
example/lib/main.dart
example/pubspec.yaml

Added the integration test for flutter.
Modified pipeline jobs to run the test in Android emulator and iOS simulator
https://rokt.atlassian.net/browse/MP-1647
Tested on CircleCi

Added the flutter UI test and update circle ci pipeline

---

CHANGELOG.md
android/build.gradle
pubspec.yaml

Updated Rokt Sdk to 3.7.0
https://rokt.atlassian.net/browse/MP-1566

update Rokt sdk to 3.7.0

---

CHANGELOG.md
README.md
example/ios/Runner/Info.plist
ios/rokt_sdk.podspec

Rokt iOS SDK version 3.7.0 released
Flutter SDK updated to reflect the iOS changes

update version 3.7.0

---

.circleci/config.yml

Updated the Android build machine.

updated build machine android

---

CHANGELOG.md
README.md
android/build.gradle
example/integration_test/app_test.dart
example/lib/main.dart
ios/rokt_sdk.podspec
pubspec.yaml

Updated Rokt Sdk version to 3.8.0
https://rokt.atlassian.net/browse/EINT-135

Changed sdk version to 3.8.0 and updated native sdk version to 3.8.0

---

.circleci/config.yml
CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

- Updated Rokt native sdk to 3.9.0
- Updated Flutter sdk to 3.9.0
https://rokt.atlassian.net/browse/EINT-334

updated rokt sdk version to 3.9.0

---

CHANGELOG.md
README.md
android/build.gradle
pubspec.yaml

Updated Flutter Sdk to 3.9.1
Updated Android sdk to 3.9.1
https://rokt.atlassian.net/browse/EINT-431

updated android sdk version 3.9.1

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

- Updated to 3.10.0
https://rokt.atlassian.net/browse/EINT-569

EINT-569 updated to 3.10.0

---

example/integration_test/app_test.dart

iOS test are failing, still investigation going on. 
Created ticket:
https://rokt.atlassian.net/browse/EINT-574

commenting test

---

CHANGELOG.md
README.md
example/integration_test/app_test.dart
pubspec.yaml

* Verification for pipelines
https://rokt.atlassian.net/browse/EINT-594

updated sdk version

---

CHANGELOG.md
README.md
pubspec.yaml

Updating sdk alpha version
Updated changelog, readme and pubspec to version 3.10.1-alpha.2
New pre-release version in pub.dev

update version to 3.10.1-alpha.2

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

Update to SDK version 3.11.0
Update dependencies, pubspec and docs for SDK version 3.11.0

Update to 3.11.0

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

Update for sdk 3.12.0
Updated podspec, gradle and docs for version 3.12.0

update for sdk 3.12.0

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

Version 3.13.0
Updated versions in pubspec and podspec to 3.13.0 and CHANGELOG

bump versions and readme for 3.13.0

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

Update the Flutter SDK package to 3.14.0
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2174))]
Updated flutter version to 3.14.0

MP-2174 Release SDK version 3.14.0

---

CHANGELOG.md
README.md
ios/rokt_sdk.podspec
pubspec.yaml

Need to release flutter version 3.14.2
iOS SDK updated to version 3.14.2

update to version 3.14.2

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

Updated Rokt SDK version to 3.15.0.
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2325))]

MP-2217 Updated Rokt Native Versions

---

CHANGELOG.md
README.md
android/build.gradle
example/android/app/build.gradle
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/kotlin/com/rokt/rokt_sdk_example/MainActivity.kt
example/android/app/src/main/res/xml/network_security_config.xml
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/ios/Runner.xcodeproj/project.pbxproj
ios/rokt_sdk.podspec
pubspec.yaml

Updates for release 4.0.0-alpha.3 which introduces layouts
- Bump SDK version up to 4.0.0-alpha.3
- Add dependency requirements to README to integrate from 4.0.0 onwards. Sample app updated to match these requirements
- Use FlutterFragmentActivity instead of FlutterActivity to prevent crash on embedded layouts
Rendered Mobile team's production layouts locally

Update for release 4.0.0 alpha

---

CHANGELOG.md
README.md
android/build.gradle
ios/rokt_sdk.podspec
pubspec.yaml

Update to version 3.15.4
Updated native dependencies, version, readme and changelog
Ran sample app locally

update to sdk version 3.15.4

---

CHANGELOG.md
README.md
android/build.gradle
pubspec.yaml

Update Android SDK version to 3.15.5
Fixes [MP-2667](https://rokt.atlassian.net/browse/MP-2667)
SDK version update

MP-2667 - Update SDK version to 3.15.5

---

.buildkite/bin/create_tag.sh
.buildkite/bin/update_changelog.sh
.buildkite/bin/update_versions.sh
.buildkite/release.pipeline.yml
README.md

Adding automated release pipeline. 
Fixes [MP-2599](https://rokt.atlassian.net/browse/MP-2599)
- Added automated pipeline with tagging 
- Added script to update the changelog from bk metadata, it skips if the provided text is empty to allow for manual updates in the repo itself
Tested with a dry run: https://buildkite.com/rokt/rokt-flutter-sdk/builds/136
Checked tag

[MP-2599] Automated Release Pipeline

---

android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/res/xml/network_security_config.xml
example/ios/Runner.xcodeproj/project.pbxproj
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec

This PR is to send Flutter as framework type
Fixes [([issue](https://rokt.atlassian.net/browse/MP-2639))]

MP-2639 Record Flutter Platform Type

---

android/build.gradle
example/android/app/build.gradle

Update compile sdk version to 34 to fix build failure
Fixes https://rokt.atlassian.net/browse/MP-3006
Built locally

fix android compile sdk version

---

.buildkite/bin/create_tag.sh
.buildkite/bin/update_changelog.sh
.buildkite/bin/update_versions.sh
.buildkite/release.pipeline.yml
README.md
android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec

Add release pipeline to this branch
Fixes https://rokt.atlassian.net/browse/MP-3008

add release pipeline

---

.buildkite/release.pipeline.yml

Need to set region for release pipeline
Upgraded plugin version and set region

set region aws-sm

---

android/build.gradle

Updated the maven URL for Android SDK
Fixes [([issue](https://rokt.atlassian.net/browse/MP-3087))]
Tested locally, build passed

Update Maven Url

---

.buildkite/pipeline.yml
.buildkite/release.pipeline.yml

The new fvm version needs some change in the command. Add `yes` to proceed the `fvm use` command
Fix pipeline error

[NO-JIRA] Fix the fvm command issue

---

.buildkite/release.pipeline.yml

fix publishing with the release pipeline

fix release pipeline

---

.buildkite/pipeline.yml
android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
android/src/main/kotlin/com/rokt/rokt_sdk/TextureSurfaceViewUtil.kt
example/integration_test/app_test.dart
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
ios/Classes/RoktMethodCallHandler.swift
ios/Classes/SwiftRoktSdkPlugin.swift
ios/rokt_sdk.podspec
lib/src/rokt_widget.dart

This PR is to integrate iOS partner Events.
Fixes [([issue](https://rokt.atlassian.net/browse/MP-3270))]

MP-3270 iOS/Android Events Integrations

---

android/build.gradle
pubspec.yaml

* Update the max dart version support to 4.0.0
* Change the Android compile sdk version to 33.
Update required versions

NoJira - Update the supported versions

---

lib/rokt_sdk.dart
lib/src/rokt_widget.dart
pubspec.yaml

Merge to master again
Fixes [NO-JIRA]
Merge

[NO-JIRA] Merge 4.3.x to master

---

.cortex/catalog/flutter-sdk.yaml

Add cortex configuration metadata to the repository
NA

MP-3478 - Add cortex config

---

.gitignore
android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec
lib/rokt_sdk.dart
lib/src/rokt_sdk_controller.dart

Merging Rokt config changes to release branch.
Fixes [CI-91](https://rokt.atlassian.net/browse/CI-91)

[CI-91] Merge Config Changes 

---

README.md

Adding RoktConfig to README.
Also fixing a typo.
Fixes [NO-JIRA]
Updated README
Some merging

[NO-JIRA] Update README

---

.gitignore
README.md
android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec
lib/rokt_sdk.dart
lib/src/rokt_sdk_controller.dart
lib/src/rokt_widget.dart
pubspec.yaml

Merging release 4.4.x to maste
Fixes [NO-JIRA]
Merge
Had to make a copy to fix merge conflicts

[NO-JIRA] Merge release-4.4.x to master

---

.cortex/catalog/flutter-sdk.yaml

This PR is to update Cortex Team name.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-52))]

NI-52 update team name in cortex

---

ios/rokt_sdk.podspec
pubspec.yaml

Now that we are using swift packages, the minimum supported ios version is 12. 
This is to bump it in the podspec file.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-361))]

NI-361 - update min ios version

---

android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec
lib/rokt_sdk.dart
lib/src/rokt_sdk_controller.dart

* Add `CacheConfig` in Rokt Flutter SDK
* Implement the wrapper to support extra cache config attributes
Fixes [LAYOUT-1642](https://rokt.atlassian.net/browse/LAYOUT-1642)
Add cache API support
Tested locally

LAYOUT-1642 - Add caching support in Flutter SDK

---

android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt

Fix the issue with events when multiple execute calls are performed.
Fixes [LAYOUT-1814](https://rokt.atlassian.net/browse/LAYOUT-1814)
A new subscription to the `Rokt.events()` was happening on each execute.
And since the `LifecycleOwner`(which is the activity) stays, it won't be unsubscribed. Use the existing subscription if the job is active
Tested locally

LAYOUT-1814 - Fix the duplicate events issue when execute is called multiple times

---

.buildkite/pipeline.yml
.buildkite/release.pipeline.yml
android/build.gradle
android/src/main/AndroidManifest.xml
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties

This PR is to add update the AGP version to 8.1.2 and adding the required `namespace` property in module gradle file.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-451))]

updated AGP version

---

android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
example/android/build.gradle
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec

Implement the OpenUrl event support
Implement the OpenUrl event support
Fixes [LAYOUT-2197](https://rokt.atlassian.net/browse/LAYOUT-2197)
* Updated `android/build.gradle` to add a new maven repository for Central Portal Snapshots
* Updated native SDK version that supports Open
Tested with mock responses and passthrough attribute.

LAYOUT-2197 - Add support for OpenUrl event

---

.github/workflows/pull_request.yml
.trunk/.gitignore
.trunk/configs/.hadolint.yaml
.trunk/configs/.markdownlint.yaml
.trunk/configs/.shellcheckrc
.trunk/configs/.yamllint.yaml
.trunk/trunk.yaml
android/build.gradle
android/src/main/kotlin/com/rokt/rokt_sdk/MethodCallHandlerImpl.kt
example/Gemfile.lock
example/android/build.gradle
example/integration_test/app_test.dart
example/ios/Gemfile.lock
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/lib/main.dart
example/pubspec.yaml
ios/Classes/RoktMethodCallHandler.swift
ios/rokt_sdk.podspec

Migrate checks to Github Actions and create main branch. For ease I've branched off the 4.9.0 branch with the intention of releasing from main.
- Github actions
- Passed on Github Actions
N/A

NOJIRA - GitHub actions pull request

---

.buildkite/release.pipeline.yml

- update ruby version
- and java sdk 17

update release pipeline

---

README.md

update readme 
Fixes [([issue](https://rokt.atlassian.net/browse/NI-776))]

NI-776 - update flutter readme

---

.cortex/catalog/flutter-sdk.yaml
.github/CODEOWNERS
.trunk/trunk.yaml
README.md

Update CODEOWNERS and cortex catalog to reflect the new team name
Describe the tests that you ran to verify your changes.

NoJira - Update ownership and team

---

.github/workflows/draft-release-publish.yml

Use linux compatible sed command

SQDSDKS-7310 - Use linux compatible sed command
